site_name: Prairie Documentation

site_url: https://noemiadev.github.io/Prairie/

theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - Requêtes HTTP: requetesHTTP.md
  - Vérification: verification.md
